# Generated by Django 4.2.5 on 2023-12-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_hippo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pil_cropper',
            name='pil_crop_height',
            field=models.IntegerField(blank=True, db_column='pil_crop_height', null=True),
        ),
        migrations.AddField(
            model_name='pil_cropper',
            name='pil_crop_width',
            field=models.IntegerField(blank=True, db_column='pil_crop_width', null=True),
        ),
    ]
